### ISSUE TITLE
Documentation system

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/ec-api-proxy#3]
Investigate a system for maintaining technical docs - we sue blueprint elsewhere. OpenAPI might not work as we're not strictly REST in all places - e.g a postcode page might return an address picker or a polling station result.

**Comment by chris48s** [comment]
Sym has already alluded to it here, but just to give a bit more background on why I (we) chose API Blueprint for documenting the WDIV and devs.DC APIs for others that might be working on this:

What Swagger/OpenAPI type docs are really good for is saying:

- "Here is the structure of a person object".
- "Here is the structure of a party object".
- "Here is the structure of a election object"
- etc

This maps really well on to a sitation where you've got a `/person/<person_id>` endpoint that returns a person, a `/party/<party_id>` endpoint that returns a party, etc (and maybe allows you to PUT/PATCH to update it), etc. This is basically the model we've got for something like YNR which has something close to a one-to-one mapping between DB tables and API endpoints.

With the WDIV and devs.DC APIs, the `/postcode/<postcode>` and `/address/<uprn>` endpoints return the same response, and although the object that comes back always consistently has the exact same structure, what is really useful is to be able to say:

- "Here's what a call to `/postcode/<postcode>` looks like when there are no upcoming elections in this area": https://developers.democracyclub.org.uk/api/v1/#postcode-search-no-upcoming-ballots-3
- "Here's what a call to `/postcode/<postcode>` looks like when there is an upcoming election in this area": https://developers.democracyclub.org.uk/api/v1/#postcode-search-results-found-3
- "Here's what a call to `/postcode/<postcode>` looks like when you need to show an address picker to get a result": https://developers.democracyclub.org.uk/api/v1/#postcode-search-address-picker-3

i.e: Multiple documented example responses for the same endpoint. Also worth noting this really really doesn't map on to the underlying DB structure in any meaningful way (and that is a good thing).

Most OpenAPI/Swagger-ey type things I've seen allow you to supply at most one example response per field or endpoint you're documenting so this is where the slightly more flexible nature of API Blueprint was really useful and why I think that was the right solution for documenting the WDIV and devs.DC APIs (but equally, it is not what I would have used for YNR, for example - going down the Swagger/OpenAPI route was the right choice there). I think giving multiple examples of possible outcomes of calling the `/postcode` endpoint is quite important and in general we've had quite good feedback on the quality of the API docs from users who have built stuff on the devs.DC API. That said, it is up to you and there's probably more than one way to skin this cat (for example you could communicate the same info by splitting the docs into an API 'reference' and a 'tutorial' and use different tooling).

That said, probably the main downside to APIBP is the lack of a native python parser. I do maintain [a library](https://github.com/chris48s/django-apiblueprint-view) for using it in django, but fundamentally it relies on a python binding to an underlying C library. As of 2.2.1 I do now distribute a manylinux shared object in the wheel which makes the setup/deployment easier on linux but if you care about developing on a mac you still have to compile it (or maybe `brew` works??) and it might still be a PITA to deploy to Lambda (tbh now the `.so` is in the wheel, you might be able to get away with just `pip install`-ing it and whacking it on Lambda - I've not actually tested it). So y'know.. swings and roundabouts.

**Comment by chris48s** [comment]
One further point which I forgot about last night but has surfaced as this rattled around in my brain is this:

It is difficult to explain the behaviour of this API by providing example calls based on live data because the results inherently vary over time (i.e: the response from `/postcode/SW1A1AA` today might not be the same as the response from `/postcode/SW1A1AA`tomorrow). Right now, every postcode is an example of the "no upcoming elections" response. Then this year once the May elections become "current" basically every postcode becomes an example of the "upcoming elections found, but polling station not known" response. Then gradually over time more and more postcodes will become an example of "polling station known" or "address picker needed" in a relatively unpredictable way. Then after polling day, every postcode goes back to being "no upcoming elections". This means you can't really rely on examples of live data for documentation purposes in a consistent way. The example responses (and the API sandbox) are super-important for being able to explain the cases a client app needs to handle.

By contrast, although the exact data at https://candidates.democracyclub.org.uk/api/next/people/100/ can change over time as edits are performed by users, https://candidates.democracyclub.org.uk/api/next/people/100/ is pretty much always going to return something that looks like a person object, so there is a greater extent to which you can rely on the live API to be self-documenting.

**Comment by symroe** [comment]
MVP done in Blueprint - still seems like about the best option, and it's something we're already using :+1:
